version: '3.8'

services:
  #PHP Service
  platform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: platform
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

#Nginx Service
  webserver:
      image: nginx:alpine
      container_name: webserver
      restart: unless-stopped
      tty: true
      ports:
        - "80:80"
        - "443:443"
      volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      networks:
      - app-network


  # MySQL Service
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: platform
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - dbdata:/var/lib/mysql  # Define the volume here
    networks:
      - app-network

#phpmyadmin Service
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: unless-stopped
      ports:
        - "8080:80"
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
        PMA_USER: root
        PMA_PASSWORD: 123
      networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

# Define the volume outside of services
volumes:
  dbdata:
    driver: local
