services:
  platform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: platform
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network

  webserver:
    image: jwilder/nginx-proxy:0.6.0
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/deploy/default.conf:/etc/nginx/conf.d/default.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro  # Mount Docker socket for dynamic configuration
    networks:
      - app-network

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.7
    container_name: letsencrypt
    restart: always
    volumes:
      - ./letsencrypt/certs:/etc/nginx/certs:rw  # Mount volume for certificate storage
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Mount Docker socket for communication
    environment:
      - REUSE_PRIVATE_KEYS=true
    depends_on:
      - webserver  # Ensure webserver is started first
    networks:
      - app-network

  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: platform
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: 123
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
